# Generated by Django 2.1 on 2020-12-01 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=32)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(help_text='The id of the channel on Slack.', max_length=255, unique=True)),
                ('headline', models.CharField(help_text='Display headline for the channel.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.CharField(help_text='Timestamp of the original message used by Slack as unique identifier.', max_length=255)),
                ('data', models.TextField(help_text="The message's data", max_length=255)),
                ('channel', models.ForeignKey(help_text='Slack channel the message was posted in.', on_delete=django.db.models.deletion.CASCADE, to='randr.ChatChannel')),
            ],
            options={
                'ordering': ('-ts',),
                'get_latest_by': 'ts',
            },
        ),
    ]
